name: InventoryPages
version: 1.3.2
main: me.kevinnovak.inventorypages.InventoryPages
author: KevinNovak
description: Add pages to inventories for expansive storage!
api-version: 1.20
commands:
  pickupstash:
    description: Access your pickup stash.
    usage: /pickupstash
  fillstash:
    description: Fills your stash with 5 random items.
    usage: /fillstash